# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops.auto',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.middleware.asgi2',
        'uvicorn.middleware.wsgi',
    ],
    hookspath=[],
    hooksconfig={},
    excludes=[
        'tkinter', 'matplotlib', 'PIL', 'PyQt5', 'PySide2', 'PySide6', 'PyQt6',
        'PyQt4', 'PySide', 'wx', 'wxPython',
        'IPython', 'jedi', 'parso', 'black', 'yapf_third_party',
        'sphinx', 'docutils',
        'jupyter', 'jupyterlab', 'notebook', 'ipykernel', 'ipywidgets',
        'nbconvert', 'nbclient', 'qtconsole', 'qtpy',
        'bokeh', 'plotly', 'dash',
        'tensorflow', 'torch', 'keras', 'mxnet',
        'sklearn', 'scikit_learn', 'xgboost', 'lightgbm',
        'nltk', 'gensim', 'spacy', 'transformers',
        'cv2', 'opencv', 'opencv_python',
        'moviepy', 'scikit_image', 'skimage',
        'flask', 'django', 'tornado', 'aiohttp',
        'jinja2', 'mako', 'genshi', 'cheetah',
        'celery', 'kombu',
    ],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    exclude_binaries=False,
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
