# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops.auto',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.middleware.asgi2',
        'uvicorn.middleware.wsgi',
    ],
    hookspath=[],
    hooksconfig={},
    excludes=[
        'tkinter', 'matplotlib', 'PIL', 'numpy', 'pandas',
        'scipy', 'PyQt5', 'PySide2', 'PySide6', 'PyQt6',
        'PyQt4', 'PySide', 'wx', 'wxPython',
        'IPython', 'jedi', 'parso', 'black', 'yapf_third_party',
        'sphinx', 'docutils', 'nbformat', 'jsonschema',
        'jupyter', 'jupyterlab', 'notebook', 'ipykernel', 'ipywidgets',
        'nbconvert', 'nbclient', 'qtconsole', 'qtpy',
        'bokeh', 'plotly', 'dash',
        'zmq', 'pyzmq', 'pygments',
        'chardet', 'charset_normalizer', 'babel', 'pytz', 'tzdata',
        'dateutil', 'python_dateutil', 'datefinder',
        'sqlalchemy', 'alembic', 'psycopg2',
        'pymongo', 'redis', 'kombu', 'celery',
        'flask', 'django', 'tornado', 'aiohttp',
        'jinja2', 'mako', 'genshi', 'cheetah',
        'lxml', 'beautifulsoup4', 'bs4', 'html5lib',
        'markdown', 'mistune', 'commonmark',
        'toml', 'tomli', 'tomlkit',
        'yaml', 'PyYAML', 'ruamel',
        'cv2', 'opencv', 'opencv_python',
        'moviepy', 'scikit_image', 'skimage',
        'tensorflow', 'torch', 'keras', 'mxnet',
        'sklearn', 'scikit_learn', 'xgboost', 'lightgbm',
        'nltk', 'gensim', 'spacy', 'transformers',
        'rich',
    ],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='backend',
)
